name: Build and deploy to github pages

on:
  push:
    branches:
      - mainn # don't trigger because it is broken

jobs:
  Build:
    name: Build and deploy to github pages
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.token }}

      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build API
        run: yarn build-gh-pages && yarn push-gh-pages
